name: vanevents
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7+2
  google_fonts: ^1.1.0
  provider: ^4.1.2
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  firebase_database: ^3.1.5
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.4.6
  auto_route: ^0.5.0
  firebase_messaging: ^6.0.15
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  image_picker: ^0.6.6+1
  font_awesome_flutter: ^8.8.1
  flare_flutter: ^2.0.3
  curved_navigation_bar: ^0.3.2
  flutter_progress_button: ^1.0.0
  flutter_swiper: ^1.1.6
  flutter_local_notifications: ^1.4.3
  flutter_circular_chart: ^0.1.0
  flutter_form_builder: ^3.10.0
  intl: ^0.16.1
  platform_alert_dialog: ^1.0.0+2
  cached_network_image: ^2.2.0+1
  photo_view: ^0.9.2
  flutter_bloc: ^4.0.0
  giphy_picker: ^1.0.4
  badges: ^1.1.1
  async: ^2.4.1
  modal_progress_hud: ^0.1.3
  cloud_functions: ^0.5.0
  after_init: ^0.1.2
  custom_splash: ^0.0.2
  flutter_stripe_payment: ^0.0.12
  qr_flutter: ^3.2.0
  flutter_slidable: ^0.5.4
  screen: ^0.0.5
  majascan: ^0.3.7
  pdf: ^1.8.0
  path_provider: ^1.6.8
  share_extend: ^1.1.5
  add_2_calendar: ^1.4.0
  map_launcher: ^0.4.5
  emoji_picker: ^0.1.0
  shimmer: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  auto_route_generator: ^0.5.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/animations/easypurchase.flr
    - assets/animations/easychat.flr
    - assets/animations/dance.flr
    - assets/animations/easyscan.flr
    - assets/img/normal_user_icon.png
    - assets/img/img_not_available.jpeg
    - assets/img/vanlogo.png
    - assets/images/icon.jpg
    - assets/animations/Nope.flr
    - assets/animations/ok.flr

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: CupertinoIcons
      fonts:
        - asset: assets/fonts/cupertino/CupertinoIcons.ttf
